// <auto-generated />
using AgendaContato.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaContato.Migrations
{
    [DbContext(typeof(AGENDACONTATOSContext))]
    partial class AGENDACONTATOSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaContato.Models.CONTATO", b =>
                {
                    b.Property<int>("CONTATO_COD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CONTATO_COD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CONTATO_COD"));

                    b.Property<bool>("CONTATO_FAVORITO")
                        .HasColumnType("bit")
                        .HasColumnName("CONTATO_FAVORITO");

                    b.Property<string>("CONTATO_NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CONTATO_NOME");

                    b.Property<string>("CONTATO_NUMERO")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CONTATO_NUMERO");

                    b.Property<int>("TIPO_COD")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_COD");

                    b.HasKey("CONTATO_COD");

                    b.HasIndex("TIPO_COD");

                    b.ToTable("CONTATOS");
                });

            modelBuilder.Entity("AgendaContato.Models.CONTATOGRUPO", b =>
                {
                    b.Property<int>("CONT_GRUP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CONT_GRUP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CONT_GRUP_ID"));

                    b.Property<int>("CONTATO_ID")
                        .HasColumnType("int")
                        .HasColumnName("CONTATO_ID");

                    b.Property<int>("GRUPO_ID")
                        .HasColumnType("int")
                        .HasColumnName("GRUPO_ID");

                    b.HasKey("CONT_GRUP_ID");

                    b.HasIndex("CONTATO_ID");

                    b.HasIndex("GRUPO_ID");

                    b.ToTable("CONTATOSGRUPOS");
                });

            modelBuilder.Entity("AgendaContato.Models.GRUPOCONTATO", b =>
                {
                    b.Property<int>("GRUPO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GRUPO_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRUPO_ID"));

                    b.Property<string>("GRUPO_NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GRUPO_NOME");

                    b.HasKey("GRUPO_ID");

                    b.ToTable("GRUPOCONTATOS");
                });

            modelBuilder.Entity("AgendaContato.Models.TIPOCONTATO", b =>
                {
                    b.Property<int>("TIPO_COD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TIPO_COD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TIPO_COD"));

                    b.Property<string>("TIPO_NOME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TIPO_NOME");

                    b.HasKey("TIPO_COD");

                    b.ToTable("TIPOCONTATOS");
                });

            modelBuilder.Entity("AgendaContato.Models.CONTATO", b =>
                {
                    b.HasOne("AgendaContato.Models.TIPOCONTATO", "TIPOCONTATO")
                        .WithMany("CONTATOS")
                        .HasForeignKey("TIPO_COD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TIPOCONTATO");
                });

            modelBuilder.Entity("AgendaContato.Models.CONTATOGRUPO", b =>
                {
                    b.HasOne("AgendaContato.Models.CONTATO", "CONTATO")
                        .WithMany("CONTATOGRUPOS")
                        .HasForeignKey("CONTATO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaContato.Models.GRUPOCONTATO", "GRUPOCONTATO")
                        .WithMany("CONTATOGRUPOS")
                        .HasForeignKey("GRUPO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CONTATO");

                    b.Navigation("GRUPOCONTATO");
                });

            modelBuilder.Entity("AgendaContato.Models.CONTATO", b =>
                {
                    b.Navigation("CONTATOGRUPOS");
                });

            modelBuilder.Entity("AgendaContato.Models.GRUPOCONTATO", b =>
                {
                    b.Navigation("CONTATOGRUPOS");
                });

            modelBuilder.Entity("AgendaContato.Models.TIPOCONTATO", b =>
                {
                    b.Navigation("CONTATOS");
                });
#pragma warning restore 612, 618
        }
    }
}
